config/routes.rb
Rails.application.routes.draw do
  resources :employees
  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	class << self
		 def save_to_disk
		 	employees = Employee.all
		 	fname = "#{Rails.root}/test.txt"
		 	File.open(fname,mode="a") do |f|
			 	employees.each do |e|
			 		f.puts e.name + " , " + e.hourly_rate.to_s
			 	end
		 	end
		 end
		 	handle_asynchronously :save_to_disk
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  def save_to_disk
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:rate, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<script>
  function validateForm(){
  var x=document.forms["minWage"]["employee[rate]"].value;
  if (x < 7.25)
    {
    alert("Warning: Rate below Federal Minimum!");
    return true;
    }
}
</script>

<%= form_for(@employee, html: {:name=>"minWage", :onsubmit => "validateForm()" }) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</p>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Rate</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.rate %></td>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @employee.rate %>
</p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam20257161</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>